import { Metadata } from 'next'
import './globals.css'
import styles from './layout.module.css'
import { Noto_Sans_KR } from 'next/font/google'
import { Header } from '@/modules/Header/Header'
import { Footer } from '@/modules/Footer/Footer'
import cn from 'classnames';
import Sidebar from '@/modules/Sidebar/Sidebar'

const inter = Noto_Sans_KR({ subsets: [] })

export const metadata: Metadata = {
	title: 'Наш проект',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={cn(inter.className, styles.wrapper)}>
				<Header className={styles.header} />
				<Sidebar className={styles.sidebar} />
				<div className={styles.body}>
					{children}
				</div>
				<Footer className={styles.footer} />
			</body>
		</html>
	)
}
